

//INVOICE ACTIONS TYPES
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_PENDING = 'FETCH_INVOICES_PENDING';
export const FETCH_INVOICES_FAILED = 'FETCH_INVOICES_FAILED';
export const FILTER_INVOICES = 'FILTER_INVOICES';
export const INVOICE_SELECTED = 'INVOICE_SELECTED';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_PENDING = 'EDIT_INVOICE_PENDING';
export const EDIT_INVOICE_FAILED = 'EDIT_INVOICE_FAILED';
export const EDIT_BUTTON = 'EDIT_BUTTON';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const DELETE_INVOICE_PENDING = 'DELETE_INVOICE_PENDING';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILED = 'DELETE_INVOICE_FAILED';
   
// BUSINESS ACTION TYPES
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const CREATE_BUSINESS_FAILED = 'CREATE_BUSINESS_FAILED';
export const FETCH_BUSINESSES_PENDING = 'FETCH_BUSINESSES_PENDING';
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
export const FETCH_BUSINESSES_FAILED = 'FETCH_BUSINESSES_FAILED';
export const BUSINESS_SELECTED = 'BUSINESS_SELECTED';

// DRIVER ACTION TYPES
export const CREATE_DRIVER_SUCCESS = 'CREATE_DRIVER_SUCCESS';
export const FETCH_DRIVERS_FAILED = 'FETCH_DRIVERS_FAILED';
export const FETCH_DRIVERS_PENDING = 'FETCH_DRIVERS_PENDING';
export const FETCH_DRIVERS_SUCCESS = 'FETCH_DRIVERS_SUCCESS';
export const DRIVER_SELECTED = 'DRIVER_SELECTED';

