

//INVOICE ACTIONS TYPES
export const FETCH_INVOICES = 'FETCH_INVOICES';
export const GET_INVOICE = 'GET_INVOICE';
export const NEW_INVOICE = 'NEW_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
   
// BUSINESS ACTION TYPES
export const GET_BUSINESS_LIST = 'GET_BUSINESS_LIST';
export const GET_BUSINESS = 'GET_BUSINESS';
export const ADD_BUSINESS = 'ADD_BUSINESS';

// DRIVER ACTION TYPES
export const GET_DRIVERS_LIST = 'GET_DRIVERS_LIST';
export const GET_DRIVER = 'GET_DRIVER';
export const ADD_DRIVER = 'ADD_DRIVER';