

//INVOICE ACTIONS TYPES
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_PENDING = 'FETCH_INVOICES_PENDING';
export const FETCH_INVOICES_FAILED = 'FETCH_INVOICES_FAILED';
export const FILTER_INVOICES = 'FILTER_INVOICES';
export const INVOICE_SELECTED = 'INVOICE_SELECTED';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const DELETE_INVOICE_PENDING = 'DELETE_INVOICE_PENDING';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILED = 'DELETE_INVOICE_FAILED';
   
// BUSINESS ACTION TYPES
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS';
export const FETCH_BUSINESSES_PENDING = 'FETCH_BUSINESSES_PENDING';
export const FETCH_BUSINESSES_SUCCESS = 'FETCH_BUSINESSES_SUCCESS';
export const GET_BUSINESS_LIST = 'GET_BUSINESS_LIST';
export const GET_BUSINESS = 'GET_BUSINESS';

// DRIVER ACTION TYPES
export const GET_DRIVERS_LIST = 'GET_DRIVERS_LIST';
export const GET_DRIVER = 'GET_DRIVER';
export const ADD_DRIVER = 'ADD_DRIVER';